$noun1 = read-host "Noun"
$noun2 = read-host "Noun"
$noun3 = read-host "Noun"
$adj1 = read-host "Adjective"

write-host "Twinkle, twinkle, $adj1 $noun,"
write-host "How I wonder what you are."
write-host "Up above the $noun2 so high,"
write-host "Like a $noun3 in the sky."
write-host "Twinkle, twinkle, $adj1 $noun,"
write-host "How I wonder what you are."
